import React, { useEffect, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Building2, CheckCircle2, Landmark, LockKeyhole, ShieldCheck, Stethoscope } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { getCurrentUser, loginUser } from '../../services/dbService';

const demoAccounts = [
  { email: 'vet@sante-animale.dz', role: 'roles.veterinarian', icon: Stethoscope, tone: 'teal' },
  { email: 'wilaya@sante-animale.dz', role: 'roles.wilaya', icon: Building2, tone: 'blue' },
  { email: 'central@sante-animale.dz', role: 'roles.ministry', icon: Landmark, tone: 'navy' },
];
const paths = { VETERINARIAN: '/veterinarian', WILAYA_INSPECTOR: '/wilaya', MINISTRY_ADMIN: '/ministry', MINISTRY: '/ministry', SYSTEM_ADMIN: '/admin', ADMIN: '/admin' };

export default function LoginPage() {
  const { t, i18n } = useTranslation(); const navigate = useNavigate(); const isRtl = i18n.language === 'ar';
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { const user = getCurrentUser(); if (user?.role) navigate(paths[user.role] || '/veterinarian', { replace: true }); }, [navigate]);
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); const result = await loginUser(email, password); setLoading(false); if (result.error || !result.user) { setError(result.error || t('login.error')); return; } navigate(paths[result.user.role] || '/veterinarian', { replace: true }); };
  const chooseDemo = (account) => { setEmail(account.email); setPassword('demo'); setError(''); };
  return <div className="login-page" dir={isRtl ? 'rtl' : 'ltr'}><div className="login-visual"><div className="login-brand"><div className="brand-mark"><ShieldCheck size={22} /></div><div><strong>{t('app.shortTitle')}</strong><span>{t('app.brandLine')}</span></div></div><div className="visual-content"><p className="eyebrow">{t('login.eyebrow')}</p><h1>{t('login.title')}</h1><p>{t('login.description')}</p><div className="process-rail"><div className="process-step"><span>01</span><div><strong>{isRtl ? 'التقاط الإشارة' : 'Capturer le signal'}</strong><small>{isRtl ? 'من الطبيب البيطري في المسلخ' : 'Depuis le vétérinaire en abattoir'}</small></div></div><div className="process-line"></div><div className="process-step"><span>02</span><div><strong>{isRtl ? 'مراجعة الولاية' : 'Revue de wilaya'}</strong><small>{isRtl ? 'تحقق واعتماد قبل الرفع' : 'Vérification avant remontée'}</small></div></div><div className="process-line"></div><div className="process-step"><span>03</span><div><strong>{isRtl ? 'قرار وطني' : 'Décision nationale'}</strong><small>{isRtl ? 'مؤشرات مبنية على بيانات مؤكدة' : 'Indicateurs vérifiés'}</small></div></div></div></div><div className="login-visual-footer"><span><Activity size={15} />{isRtl ? 'رصد حي على مدار الساعة' : 'Veille active 24/7'}</span><span><LockKeyhole size={14} />{isRtl ? 'دخول محمي بالصلاحيات' : 'Accès protégé par rôle'}</span></div></div><div className="login-form-side"><div className="login-form-wrap"><div className="mobile-login-brand"><div className="brand-mark"><ShieldCheck size={21} /></div><strong>{t('app.shortTitle')}</strong></div><div className="login-heading"><p className="eyebrow">{t('login.welcome')}</p><h2>{t('nav.login')}</h2><p>{t('app.subtitle')}</p></div><form onSubmit={submit} className="login-form"><label>{t('login.email')}<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder={t('login.emailPlaceholder')} required /></label><label>{t('login.password')}<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder={t('login.passwordPlaceholder')} required /></label>{error && <div className="login-error">{error}</div>}<button className="login-submit" disabled={loading}>{loading ? t('login.loading') : t('login.submit')} {isRtl ? <ArrowLeft size={17} /> : <ArrowRight size={17} />}</button></form><div className="demo-block"><div className="demo-head"><strong>{t('login.demo')}</strong><span>{t('login.demoHint')}</span></div><div className="demo-list">{demoAccounts.map((account) => <button type="button" key={account.email} className="demo-account" onClick={() => chooseDemo(account)}><span className={`demo-icon demo-${account.tone}`}><account.icon size={15} /></span><span><strong>{account.email}</strong><small>{t(account.role)}</small></span><CheckCircle2 size={15} /></button>)}</div></div><p className="login-security"><LockKeyhole size={14} />{t('login.security')}</p></div></div></div>;
}
